import "@/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

// tRPC
import { TRPCReactProvider } from "@/trpc/react";

// Font
import { montserrat } from "@/fonts";

// Components
// import { Toaster } from "@/components/ui";
import { Navbar } from "@/components/admin/Layout";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SuperAdminLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${montserrat.className}`}>
      <body>
        <TRPCReactProvider>
          <Toaster richColors closeButton />
          <Navbar />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
